# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "786c98fe9944444acac5c785daeb2dfa"
name = "store-locator"
handle = "store-locator-179"
application_url = "https://veterans-concord-sealed-warrant.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://veterans-concord-sealed-warrant.trycloudflare.com/auth/callback",
  "https://veterans-concord-sealed-warrant.trycloudflare.com/auth/shopify/callback",
  "https://veterans-concord-sealed-warrant.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
