# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d125bd69d2b12bd08b7aa9aa94b8b5f9"
name = "store"
handle = "store-206"
application_url = "https://misc-pod-brazilian-greg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://misc-pod-brazilian-greg.trycloudflare.com/auth/callback",
  "https://misc-pod-brazilian-greg.trycloudflare.com/auth/shopify/callback",
  "https://misc-pod-brazilian-greg.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
